export const chartData = [
  {
    id: "north-gaza",
    title: "شمال غزة",
    labels: ["ضغط", "كارثة", "أزمة", "طوارئ"],
    data: [5, 15, 35, 45],
    class: "ml-7 pt-5 w-[120px]",
    imgSrc: "NorthGaza.png",
  },
  {
    id: "gaza-city",
    title: "مدينة غزة",
    labels: ["ضغط", "كارثة", "أزمة", "طوارئ"],
    data: [5, 15, 35, 45],
    class: "-mt-3 ml-4 w-[100px]",
    imgSrc: "Gaza-City.png",
  },
  {
    id: "der-albalah-city",
    title: "دير البلح",
    labels: ["ضغط", "كارثة", "أزمة", "طوارئ"],
    data: [10, 5, 40, 45],
    class: "-mt-6 mr-1 w-[80px]",
    imgSrc: "DerBalah.png",
  },
  {
    id: "khan-younes-city",
    title: "خان يونس",
    labels: ["ضغط", "كارثة", "أزمة", "طوارئ"],
    data: [10, 10, 35, 45],
    class: "-mt-4 ml-[50px] w-[160px]",
    imgSrc: "khan-younes.png",
  },
  {
    id: "rafah-city",
    title: "رفــــــــح",
    labels: ["كارثة", "أزمة", "طوارئ"],
    data: [15, 25, 60],
    class: "-mt-[35px] ml-9 w-[155px]",
    imgSrc: "rafah.png",
  },
];
