export const chartData = [
  {
    id: "north-gaza",
    title: "شمال غزة",
    labels: ["ضغط", "كارثة", "أزمة", "طوارئ"],
    data: [5, 15, 35, 45],
    class: "ml-7 pt-5 w-[145px]",
    imgSrc: "NorthGaza.png",
  },
  {
    id: "gaza-city",
    title: "مدينة غزة",
    labels: ["ضغط", "كارثة", "أزمة", "طوارئ"],
    data: [5, 15, 35, 45],
    class: "-mt-4 ml-2 w-[118px]",
    imgSrc: "Gaza-City.png",
  },
  {
    id: "der-albalah-city",
    title: "دير البلح",
    labels: ["ضغط", "كارثة", "أزمة", "طوارئ"],
    data: [10, 5, 40, 45],
    class: "-mt-7 mr-4 w-[95px]",
    imgSrc: "DerBalah.png",
  },
  {
    id: "khan-younes-city",
    title: "خان يونس",
    labels: ["ضغط", "كارثة", "أزمة", "طوارئ"],
    data: [10, 10, 35, 45],
    class: "-mt-5 ml-[50px] w-[190px]",
    imgSrc: "khan-younes.png",
  },
  {
    id: "rafah-city",
    title: "رفــــــــح",
    labels: ["كارثة", "أزمة", "طوارئ"],
    data: [15, 25, 60],
    class: "-mt-[43px] ml-8 w-[185px]",
    imgSrc: "rafah.png",
  },
];
